-- Create agent_website_settings table
CREATE TABLE IF NOT EXISTS public.agent_website_settings (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    slug TEXT UNIQUE,
    is_builder_active BOOLEAN DEFAULT false,
    html_content TEXT,
    is_custom_url_active BOOLEAN DEFAULT false,
    is_pro_active BOOLEAN DEFAULT false,
    fb_pixel_id TEXT,
    meta_title TEXT,
    meta_description TEXT,
    meta_image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Add RLS (Row Level Security)
ALTER TABLE public.agent_website_settings ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can read public agent settings (if slug is set)
CREATE POLICY "Public profiles are viewable by everyone" 
ON public.agent_website_settings FOR SELECT 
USING (slug IS NOT NULL);

-- Policy: Users can only update their own settings
CREATE POLICY "Users can insert their own settings" 
ON public.agent_website_settings FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own settings" 
ON public.agent_website_settings FOR UPDATE 
USING (auth.uid() = user_id);

-- Function to handle updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for updated_at
CREATE TRIGGER set_updated_at
BEFORE UPDATE ON public.agent_website_settings
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- Add comments for documentation
COMMENT ON TABLE public.agent_website_settings IS 'Settings for agent white-label websites';
COMMENT ON COLUMN public.agent_website_settings.slug IS 'Unique URL slug for the agent website';
COMMENT ON COLUMN public.agent_website_settings.is_builder_active IS 'Whether to use custom HTML builder content or standard template';
COMMENT ON COLUMN public.agent_website_settings.html_content IS 'Custom HTML content generated by the builder';
COMMENT ON COLUMN public.agent_website_settings.is_custom_url_active IS 'Whether the agent can use a custom slug (Premium feature)';
COMMENT ON COLUMN public.agent_website_settings.is_pro_active IS 'Whether the agent has active Premium features';
