import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { coreApi } from '@/lib/coreApi';
import { useTenantScope, tenantScopeKey } from '@/hooks/useTenantScope';
export interface AgentNotification { id:string; travel_id:string; notification_type:'new_inquiry'|'overdue_payment'|'new_booking'|'new_haji_registration'; title:string; body:string; reference_id:string|null; reference_type:string|null; is_read:boolean; read_at:string|null; created_at:string; }
const map=(row:Record<string,any>):AgentNotification=>({id:String(row.id),travel_id:String(row.travel_id||''),notification_type:row.type||'new_booking',title:String(row.title||''),body:String(row.message||row.body||''),reference_id:row.reference_id??null,reference_type:row.reference_type??null,is_read:Boolean(row.is_read),read_at:row.read_at??null,created_at:String(row.created_at)});
export const useAgentNotifications=(travelId?:string)=>{const {data:scope}=useTenantScope();const qc=useQueryClient();const q=useQuery({queryKey:['agent-notifications','core',tenantScopeKey(scope),travelId??null],queryFn:async()=>{const r=await coreApi.listMyPaymentNotifications({limit:50});return (r.data||[]).map(map);},enabled:Boolean(travelId&&scope?.tenant_id),refetchInterval:30000});return {...q,unreadCount:q.data?.filter(n=>!n.is_read).length||0};};
export const useMarkNotificationRead=()=>{const qc=useQueryClient();return useMutation({mutationFn:(id:string)=>coreApi.markMyNotificationRead(id),onSuccess:()=>{void qc.invalidateQueries({queryKey:['agent-notifications']});void qc.invalidateQueries({queryKey:['notifications']});}});};
export const useMarkAllNotificationsRead=()=>{const qc=useQueryClient();return useMutation({mutationFn:(_travelId:string)=>coreApi.markAllMyNotificationsRead(),onSuccess:()=>{void qc.invalidateQueries({queryKey:['agent-notifications']});void qc.invalidateQueries({queryKey:['notifications']});}});};
export const useTriggerNotificationCheck=()=>{const qc=useQueryClient();return useMutation({mutationFn:async()=>({accepted:true,queued:false}),onSuccess:()=>{void qc.invalidateQueries({queryKey:['agent-notifications']});}});};
