import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useAuth } from './useAuth';
import { coreApi } from '@/lib/coreApi';
import { toast } from 'sonner';
export interface ChatMessage { id:string; booking_id:string|null; travel_id:string; sender_id:string; sender_type:'jamaah'|'agent'; message:string; is_read:boolean; read_at:string|null; created_at:string; }
export const useChat=(bookingId:string|null,travelId:string|null)=>{const {user}=useAuth();const qc=useQueryClient();const messageKey=['chat-messages','core',bookingId,travelId];const {data:messages=[],isLoading}=useQuery({queryKey:messageKey,queryFn:()=>coreApi.listChatMessages({travelId:travelId!,bookingId}) as unknown as Promise<ChatMessage[]>,enabled:Boolean(travelId&&user),refetchInterval:10000});const sendMessage=useMutation({mutationFn:({message,senderType}:{message:string;senderType:'jamaah'|'agent'})=>{if(!user||!travelId)throw new Error('Not authenticated');return coreApi.sendChatMessage({booking_id:bookingId,travel_id:travelId,sender_type:senderType,message});},onSuccess:()=>{void qc.invalidateQueries({queryKey:messageKey});},onError:()=>toast.error('Gagal mengirim pesan')});const markAsRead=async()=>{if(user&&travelId){await coreApi.markChatMessagesRead({travel_id:travelId,booking_id:bookingId});void qc.invalidateQueries({queryKey:messageKey});}};const {data:unread}=useQuery({queryKey:['chat-unread','core',travelId],queryFn:async()=>{const r=await coreApi.getChatUnreadCount(travelId!);return r.count||0;},enabled:Boolean(travelId&&user),refetchInterval:10000});return {messages,isLoading,sendMessage,markAsRead,unreadCount:unread||0};};
export interface ChatConversation { booking_id: string | null; last_message: string; last_message_time: string; unread_count: number }

export const useAgentChats=(travelId:string|null)=>{const {user}=useAuth();return useQuery({queryKey:['agent-chats','core',travelId],queryFn:async()=>(await coreApi.listChatConversations()) as unknown as ChatConversation[],enabled:Boolean(travelId&&user),refetchInterval:15000});};
