import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useAuthContext } from '@/contexts/AuthContext';
import { usePremiumTrialConfig } from '@/hooks/usePremiumConfig';
import { useIsPremium } from '@/hooks/usePremiumSubscription';
import { coreApi } from '@/lib/coreApi';
interface TrialStatus { isInTrial:boolean; daysRemaining:number; trialStartDate:string|null; trialEndDate:string|null; hasTrialExpired:boolean; hasEverStartedTrial:boolean; trialDurationDays:number; trialEnabled:boolean; }
const EMPTY:TrialStatus={isInTrial:false,daysRemaining:0,trialStartDate:null,trialEndDate:null,hasTrialExpired:false,hasEverStartedTrial:false,trialDurationDays:30,trialEnabled:true};
export const useFreeTrial=()=>{const {user}=useAuthContext();const qc=useQueryClient();const {data:config}=usePremiumTrialConfig();const durationDays=config?.durationDays??30;const trialEnabled=config?.enabled??true;const {data,status,isLoading}=useQuery({queryKey:['free-trial','core',user?.id??null,durationDays,trialEnabled],queryFn:async():Promise<TrialStatus>=>{const base={trialDurationDays:durationDays,trialEnabled};const sub=status==='success'?status:null;const s=await coreApi.getPremiumSubscriptionPlanStatus();const current=s.subscription as Record<string,any>|null;if(!current)return {...EMPTY,...base};const start=current.current_period_start?String(current.current_period_start):null;const end=current.current_period_end?String(current.current_period_end):null;const inTrial=current.status==='trial'&&Boolean(end)&&new Date(end)>new Date();return {...EMPTY,...base,isInTrial:inTrial,daysRemaining:inTrial?Math.max(0,Math.ceil((new Date(end!).getTime()-Date.now())/86400000)):0,trialStartDate:start,trialEndDate:end,hasTrialExpired:current.status==='trial'&&!inTrial,hasEverStartedTrial:current.status==='trial'||Boolean(start)};},enabled:Boolean(user?.id)});const startTrial=useMutation({mutationFn:()=>{if(!user?.id)throw new Error('Not authenticated');if(!trialEnabled)throw new Error('Trial is disabled');return coreApi.startFreeTrial();},onSuccess:()=>{void qc.invalidateQueries({queryKey:['free-trial']});void qc.invalidateQueries({queryKey:['user-subscription']});}});return {...(data||{...EMPTY,trialDurationDays:durationDays,trialEnabled}),isLoading,startTrial};};
export const useHasPremiumAccess=()=>{const {isInTrial}=useFreeTrial();const {isPremium}=useIsPremium();const {isAdmin}=useAuthContext();return {hasPremiumAccess:isAdmin()||isPremium||isInTrial};};
