import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useAuthContext } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';
import { useTenantScope, tenantScopeKey } from '@/hooks/useTenantScope';
import { coreApi } from '@/lib/coreApi';

export type PackageType = 'umroh' | 'haji_reguler' | 'haji_plus' | 'haji_furoda';
export interface HajiRegistration { id: string; user_id: string | null; package_id: string | null; travel_id: string | null; full_name: string; nik: string; phone: string; email: string | null; birth_date: string; address: string | null; porsi_number?: string | null; registration_year?: number | null; estimated_departure_year?: number | null; status: 'pending' | 'verified' | 'waiting' | 'departed' | 'cancelled' | 'registered' | 'called' | 'departing' | 'completed'; documents?: Record<string, any>; dp_amount: number; dp_paid_at?: string | null; agent_notes?: string | null; registration_code?: string | null; registration_type?: PackageType; preferred_year?: number | null; estimated_year?: number | null; queue_number?: number | null; created_at: string; updated_at: string; package?: { name: string; package_type: PackageType }; }
export interface HajiChecklist { id: string; title: string; description: string | null; category: string; is_required: boolean; applies_to: string[]; priority: number; is_active: boolean; }
export const packageTypeLabels: Record<PackageType, string> = { umroh: 'Umroh', haji_reguler: 'Haji Reguler', haji_plus: 'Haji Plus/Khusus', haji_furoda: 'Haji Furoda' };
export const packageTypeColors: Record<PackageType, string> = { umroh: 'bg-emerald-100 text-emerald-800', haji_reguler: 'bg-blue-100 text-blue-800', haji_plus: 'bg-purple-100 text-purple-800', haji_furoda: 'bg-amber-100 text-amber-800' };

export const useHajiChecklists = (packageType?: PackageType) => useQuery({ queryKey: ['haji-checklists', 'core', packageType ?? null], queryFn: () => coreApi.listHajiChecklists(packageType) as unknown as Promise<HajiChecklist[]> });
export const useUserHajiRegistrations = () => { const { user } = useAuthContext(); return useQuery({ queryKey: ['user-haji-registrations', 'core', user?.id ?? null], queryFn: () => coreApi.listMyHajiRegistrations() as unknown as Promise<HajiRegistration[]>, enabled: Boolean(user) }); };
export const useAgentHajiRegistrations = (travelId?: string) => { const { data: scope } = useTenantScope(); const scopeKey = tenantScopeKey(scope); return useQuery({ queryKey: ['agent-haji-registrations', 'core', scopeKey, travelId ?? null], queryFn: () => coreApi.listManagementHajiRegistrations() as unknown as Promise<HajiRegistration[]>, enabled: Boolean(travelId && scope?.tenant_id) }); };
export const useSubmitHajiRegistration = () => { const { user } = useAuthContext(); const qc = useQueryClient(); const { toast } = useToast(); return useMutation({ mutationFn: (data: { packageId: string; travelId: string; fullName: string; nik: string; phone: string; email?: string; birthDate: string; address?: string; dpAmount?: number }) => { if (!user) throw new Error('Harus login untuk mendaftar haji'); return coreApi.createHajiRegistration({ package_id: data.packageId, travel_id: data.travelId, full_name: data.fullName, nik: data.nik, phone: data.phone, email: data.email ?? null, birth_date: data.birthDate, address: data.address ?? null, down_payment: data.dpAmount ?? 0 }); }, onSuccess: () => { void qc.invalidateQueries({ queryKey: ['user-haji-registrations'] }); void qc.invalidateQueries({ queryKey: ['agent-haji-registrations'] }); toast({ title: 'Pendaftaran haji berhasil dikirim' }); }, onError: (e: any) => toast({ title: 'Gagal mendaftar haji', description: e.message, variant: 'destructive' }) }); };
export const useUpdateHajiRegistration = () => { const qc = useQueryClient(); const { toast } = useToast(); return useMutation({ mutationFn: ({ registrationId, updates }: { registrationId: string; updates: { status?: HajiRegistration['status']; porsi_number?: string; estimated_departure_year?: number; agent_notes?: string; documents?: Record<string, any>; } }) => coreApi.updateHajiRegistration(registrationId, { status: updates.status === 'pending' ? 'registered' : updates.status === 'verified' ? 'waiting' : updates.status === 'departed' ? 'departing' : updates.status, estimated_year: updates.estimated_departure_year, notes: updates.agent_notes, meta_data: updates.documents }), onSuccess: () => { void qc.invalidateQueries({ queryKey: ['agent-haji-registrations'] }); void qc.invalidateQueries({ queryKey: ['user-haji-registrations'] }); toast({ title: 'Data haji berhasil diperbarui' }); }, onError: (e: any) => toast({ title: 'Gagal memperbarui data haji', description: e.message, variant: 'destructive' }) }); };
export const useHajiStats = (travelId?: string) => { const { data: scope } = useTenantScope(); return useQuery({ queryKey: ['haji-stats', 'core', tenantScopeKey(scope), travelId ?? null], queryFn: () => coreApi.getHajiStats(), enabled: Boolean(travelId && scope?.tenant_id) }); };
export const getHajiSeasonInfo = () => { const now = new Date(); const currentYear = now.getFullYear(); const isHajiSeason = now.getMonth() >= 6 && now.getMonth() <= 8; return { currentYear, nextHajiYear: isHajiSeason ? currentYear + 1 : currentYear, isHajiSeason, estimatedHajiMonths: ['Juli', 'Agustus'], regularWaitingYears: 25 }; };
