import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/hooks/useAuth';
import { coreApi } from '@/lib/coreApi';

export type JournalMood = 'grateful' | 'peaceful' | 'emotional' | 'inspired' | 'tired' | 'happy';
export interface Journal { id: string; user_id: string; title: string; content: string | null; location_name: string | null; latitude: number | null; longitude: number | null; mood: JournalMood | null; is_public: boolean; created_at: string; updated_at: string; photos?: JournalPhoto[]; }
export interface JournalPhoto { id: string; journal_id: string; photo_url: string; caption: string | null; order_index: number; created_at: string; }
export interface CreateJournalInput { title: string; content?: string; location_name?: string; latitude?: number; longitude?: number; mood?: JournalMood; is_public?: boolean; }
export interface UpdateJournalInput extends Partial<CreateJournalInput> { id: string; }
const journalKey = ['journals', 'core'] as const;
const journalDetailKey = (id: string | null) => ['journal', 'core', id] as const;

export const useJournals = () => { const { user } = useAuth(); return useQuery({ queryKey: [...journalKey, user?.id ?? null], queryFn: () => coreApi.listJournals() as Promise<Journal[]>, enabled: Boolean(user) }); };
export const useJournal = (journalId: string | null) => useQuery({ queryKey: journalDetailKey(journalId), queryFn: () => coreApi.getJournal(journalId!) as Promise<Journal>, enabled: Boolean(journalId) });
export const useCreateJournal = () => { const qc = useQueryClient(); const { toast } = useToast(); const { user } = useAuth(); return useMutation({ mutationFn: (input: CreateJournalInput) => { if (!user) throw new Error('User not authenticated'); return coreApi.createJournal(input); }, onSuccess: () => { void qc.invalidateQueries({ queryKey: journalKey }); toast({ title: 'Jurnal Tersimpan', description: 'Catatan jurnal berhasil disimpan' }); }, onError: (e: any) => toast({ title: 'Gagal Menyimpan', description: e.message, variant: 'destructive' }) }); };
export const useUpdateJournal = () => { const qc = useQueryClient(); const { toast } = useToast(); return useMutation({ mutationFn: ({ id, ...input }: UpdateJournalInput) => coreApi.updateJournal(id, input), onSuccess: (data: any) => { void qc.invalidateQueries({ queryKey: journalKey }); if (data?.id) void qc.invalidateQueries({ queryKey: journalDetailKey(data.id) }); toast({ title: 'Jurnal Diperbarui', description: 'Perubahan berhasil disimpan' }); }, onError: (e: any) => toast({ title: 'Gagal Memperbarui', description: e.message, variant: 'destructive' }) }); };
export const useDeleteJournal = () => { const qc = useQueryClient(); const { toast } = useToast(); return useMutation({ mutationFn: (journalId: string) => coreApi.deleteJournal(journalId), onSuccess: () => { void qc.invalidateQueries({ queryKey: journalKey }); toast({ title: 'Jurnal Dihapus', description: 'Catatan jurnal berhasil dihapus' }); }, onError: (e: any) => toast({ title: 'Gagal Menghapus', description: e.message, variant: 'destructive' }) }); };
export const useUploadJournalPhoto = () => { const qc = useQueryClient(); const { toast } = useToast(); const { user } = useAuth(); return useMutation({ mutationFn: async ({ file, journalId, caption, order_index }: { file: File; journalId: string; caption?: string | null; order_index?: number }) => { if (!user) throw new Error('User not authenticated'); return coreApi.uploadJournalPhotoPresigned(journalId, file, caption, order_index); }, onSuccess: (_data, variables) => { void qc.invalidateQueries({ queryKey: journalKey }); void qc.invalidateQueries({ queryKey: journalDetailKey(variables.journalId) }); toast({ title: 'Foto jurnal berhasil diupload' }); }, onError: (e: any) => toast({ title: 'Gagal Upload Foto', description: e.message, variant: 'destructive' }) }); };
export const useDeleteJournalPhoto = () => { const qc = useQueryClient(); const { toast } = useToast(); return useMutation({ mutationFn: ({ journalId, photoId }: { journalId: string; photoId: string }) => coreApi.deleteJournalPhoto(journalId, photoId), onSuccess: (_data, variables) => { void qc.invalidateQueries({ queryKey: journalKey }); void qc.invalidateQueries({ queryKey: journalDetailKey(variables.journalId) }); }, onError: (e: any) => toast({ title: 'Gagal Menghapus Foto', description: e.message, variant: 'destructive' }) }); };
export const getMoodEmoji = (mood: JournalMood): string => ({ grateful: '🤲', peaceful: '☮️', emotional: '🥹', inspired: '✨', tired: '😴', happy: '😊' })[mood];
export const getMoodLabel = (mood: JournalMood): string => ({ grateful: 'Bersyukur', peaceful: 'Damai', emotional: 'Haru', inspired: 'Terinspirasi', tired: 'Lelah', happy: 'Bahagia' })[mood];
