import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { coreApi } from '@/lib/coreApi';
export interface PremiumTrialConfig { enabled:boolean; durationDays:number; }
const DEFAULT_TRIAL_CONFIG:PremiumTrialConfig={enabled:true,durationDays:30};
export const usePremiumTrialConfig=()=>useQuery({queryKey:['premium-trial-config','core'],queryFn:async()=>{const status=await coreApi.getPremiumSubscriptionPlanStatus();const limits=(status?.plan?.limits||{}) as Record<string,unknown>;return {enabled:limits.trial_enabled===undefined?DEFAULT_TRIAL_CONFIG.enabled:Boolean(limits.trial_enabled),durationDays:Number(limits.trial_duration_days||DEFAULT_TRIAL_CONFIG.durationDays)};},staleTime:300000});
export const useSavePremiumTrialConfig=()=>{const qc=useQueryClient();return useMutation({mutationFn:(config:PremiumTrialConfig)=>coreApi.updatePlatformAdminSetting('premium_trial_config',config),onSuccess:()=>{void qc.invalidateQueries({queryKey:['premium-trial-config']});void qc.invalidateQueries({queryKey:['free-trial']});}});};
export interface PremiumPlanConfig { name:string; description:string; priceYearly:number; features:string[]; }
const DEFAULT_PLAN_CONFIG:PremiumPlanConfig={name:'Premium Ibadah Tracker',description:'Akses penuh fitur cloud & statistik',priceYearly:29000,features:['Sync data ke cloud','Backup otomatis','Akses multi-device','Statistik lengkap','Export data']};
export const usePremiumPlanConfig=()=>useQuery({queryKey:['premium-plan-config','core'],queryFn:async()=>{const plans=await coreApi.listSubscriptionPlans() as Array<Record<string,any>>;const plan=plans.find(p=>p.code==='premium')||plans.find(p=>p.billing_interval==='yearly')||plans[0];return plan?{name:plan.name||DEFAULT_PLAN_CONFIG.name,description:plan.description||DEFAULT_PLAN_CONFIG.description,priceYearly:Number(plan.price_minor||DEFAULT_PLAN_CONFIG.priceYearly),features:Array.isArray(plan.features)&&plan.features.length?plan.features:DEFAULT_PLAN_CONFIG.features}:DEFAULT_PLAN_CONFIG;},staleTime:300000});
export const useSavePremiumPlanConfig=()=>{const qc=useQueryClient();return useMutation({mutationFn:(config:PremiumPlanConfig)=>coreApi.updatePlatformAdminSetting('premium_plan_config',config),onSuccess:()=>{void qc.invalidateQueries({queryKey:['premium-plan-config']});void qc.invalidateQueries({queryKey:['subscription-plans']});}});};
