import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useToast } from '@/hooks/use-toast';
import { coreApi } from '@/lib/coreApi';

export interface PrayerCategory { id: string; name: string; name_arabic: string | null; description: string | null; icon: string | null; priority: number; is_active: boolean; created_at: string; updated_at: string; }
export interface Prayer { id: string; category_id: string | null; title: string; title_arabic: string | null; arabic_text: string; transliteration: string | null; translation: string | null; source: string | null; benefits: string | null; audio_url: string | null; priority: number; is_active: boolean; created_at: string; updated_at: string; category?: PrayerCategory | null; }

type PrayerInput = Omit<Prayer, 'id' | 'created_at' | 'updated_at' | 'category'>;
type CategoryInput = Omit<PrayerCategory, 'id' | 'created_at' | 'updated_at'>;
const key = { categories: ['prayer-categories', 'core'] as const, adminCategories: ['admin-prayer-categories', 'core'] as const, prayers: (categoryId?: string) => ['prayers', 'core', categoryId ?? null] as const, adminPrayers: ['admin-prayers', 'core'] as const, prayer: (id: string | null) => ['prayer', 'core', id] as const };
const invalidate = (qc: ReturnType<typeof useQueryClient>) => { void qc.invalidateQueries({ queryKey: ['prayer-categories'] }); void qc.invalidateQueries({ queryKey: ['admin-prayer-categories'] }); void qc.invalidateQueries({ queryKey: ['prayers'] }); void qc.invalidateQueries({ queryKey: ['admin-prayers'] }); void qc.invalidateQueries({ queryKey: ['prayer'] }); };

export const usePrayerCategories = () => useQuery({ queryKey: key.categories, queryFn: () => coreApi.listPrayerCategories(false) as unknown as Promise<PrayerCategory[]> });
export const useAllPrayerCategories = () => useQuery({ queryKey: key.adminCategories, queryFn: () => coreApi.listPrayerCategories(true) as unknown as Promise<PrayerCategory[]> });
export const usePrayers = (categoryId?: string) => useQuery({ queryKey: key.prayers(categoryId), queryFn: () => coreApi.listPrayers(false, categoryId) as unknown as Promise<Prayer[]> });
export const useAllPrayers = () => useQuery({ queryKey: key.adminPrayers, queryFn: () => coreApi.listPrayers(true) as unknown as Promise<Prayer[]> });
export const usePrayer = (prayerId: string | null) => useQuery({ queryKey: key.prayer(prayerId), queryFn: () => coreApi.getPrayer(prayerId!) as unknown as Promise<Prayer>, enabled: Boolean(prayerId) });

export const useCreatePrayerCategory = () => { const qc = useQueryClient(); const { toast } = useToast(); return useMutation({ mutationFn: (category: CategoryInput) => coreApi.createPrayerCategory(category), onSuccess: () => { invalidate(qc); toast({ title: 'Kategori berhasil ditambahkan' }); }, onError: (e: any) => toast({ title: 'Gagal menambahkan kategori', description: e.message, variant: 'destructive' }) }); };
export const useUpdatePrayerCategory = () => { const qc = useQueryClient(); const { toast } = useToast(); return useMutation({ mutationFn: ({ id, ...data }: Partial<PrayerCategory> & { id: string }) => coreApi.updatePrayerCategory(id, data), onSuccess: () => { invalidate(qc); toast({ title: 'Kategori berhasil diperbarui' }); }, onError: (e: any) => toast({ title: 'Gagal memperbarui kategori', description: e.message, variant: 'destructive' }) }); };
export const useDeletePrayerCategory = () => { const qc = useQueryClient(); const { toast } = useToast(); return useMutation({ mutationFn: (id: string) => coreApi.deletePrayerCategory(id), onSuccess: () => { invalidate(qc); toast({ title: 'Kategori berhasil dihapus' }); }, onError: (e: any) => toast({ title: 'Gagal menghapus kategori', description: e.message, variant: 'destructive' }) }); };
export const useCreatePrayer = () => { const qc = useQueryClient(); const { toast } = useToast(); return useMutation({ mutationFn: (prayer: PrayerInput) => coreApi.createPrayer(prayer), onSuccess: () => { invalidate(qc); toast({ title: 'Doa berhasil ditambahkan' }); }, onError: (e: any) => toast({ title: 'Gagal menambahkan doa', description: e.message, variant: 'destructive' }) }); };
export const useUpdatePrayer = () => { const qc = useQueryClient(); const { toast } = useToast(); return useMutation({ mutationFn: ({ id, category, ...data }: Partial<Prayer> & { id: string }) => coreApi.updatePrayer(id, data), onSuccess: () => { invalidate(qc); toast({ title: 'Doa berhasil diperbarui' }); }, onError: (e: any) => toast({ title: 'Gagal memperbarui doa', description: e.message, variant: 'destructive' }) }); };
export const useDeletePrayer = () => { const qc = useQueryClient(); const { toast } = useToast(); return useMutation({ mutationFn: (id: string) => coreApi.deletePrayer(id), onSuccess: () => { invalidate(qc); toast({ title: 'Doa berhasil dihapus' }); }, onError: (e: any) => toast({ title: 'Gagal menghapus doa', description: e.message, variant: 'destructive' }) }); };
export const useUploadPrayerAudio = () => { const { toast } = useToast(); return useMutation({ mutationFn: async ({ file }: { file: File; prayerId: string }) => { if (!file.type.startsWith('audio/')) throw new Error('Hanya file audio yang diperbolehkan'); const data = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error('File audio tidak dapat dibaca')); reader.readAsDataURL(file); }); const uploaded = await coreApi.uploadPublicAsset({ data, contentType: file.type, filename: file.name, bucket: 'prayer-audio' }); return uploaded.publicUrl || uploaded.url; }, onError: (e: any) => toast({ title: 'Gagal upload audio', description: e.message, variant: 'destructive' }) }); };
